variables:
  BuildConfiguration: 'Release'
  CI: true

trigger:
  branches:
    include:
      - main
      - dev
  paths:
    exclude:
    - infrastructure/
pr: [ 'main', 'dev' ]

jobs:
  - job: 'Frontend'
    pool:
      vmImage: 'ubuntu-20.04'
      demands: azureps
    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js 16.14.2'
        inputs:
          versionSpec: '16.14.2'
      - task: 'Npm@1'
        displayName: 'npm run ci'
        inputs:
          command: 'custom'
          workingDir: '.'
          verbose: false
          customCommand: 'ci'
      - task: 'Npm@1'
        displayName: 'npm run bootstrap'
        inputs:
          command: 'custom'
          workingDir: '.'
          verbose: false
          customCommand: 'run bootstrap'

      - task: 'Npm@1'
        displayName: 'Build frontend'
        inputs:
          command: 'custom'
          workingDir: './src/explore-education-statistics-frontend'
          verbose: false
          customCommand: 'run build'
      - task: 'Bash@3'
        displayName: 'Remove dev dependencies'
        inputs:
          targetType: 'inline'
          script: 'rm -rf ./src/**/node_modules'
      - task: 'Npm@1'
        displayName: 'Install prod dependencies'
        inputs:
          command: 'custom'
          workingDir: '.'
          verbose: false
          customCommand: 'run bootstrap:prod'
      - task: 'ArchiveFiles@2'
        displayName: 'Archive frontend'
        inputs:
          rootFolderOrFile: './src/explore-education-statistics-frontend'
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/public-frontend.zip'
      - task: 'PublishPipelineArtifact@0'
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: 'public-frontend'
          targetPath: '$(Build.ArtifactStagingDirectory)'
